# Generated by Django 3.0 on 2021-04-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='enroll_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
